### ISSUE TITLE
Suggestion: Shift Click to Select Multiple People

### ISSUE THREAD

**Issue by shinkei13** [orcnog/autocomplete-whisper#39]
At the moment, unless you've already typed an open bracket "[" you cannot select multiple whisper targets. It would be nice to have the option to select more than one player simply by shift clicking their names.

**Comment by orcnog** [comment]
I like this suggestion.
Currently, I do plan to make this update as soon as I have the time.

**Comment by orcnog** [comment]
@shinkei13, @CeaneC, @ anyone else,
I've developed this enhancement in [this branch](https://github.com/orcnog/autocomplete-whisper/tree/shift-click-v2).  Would you guys mind helping me test it?  I've done my testing and I think it's performing well, but I'd love some community/developer feedback, particularly on the UI if you have suggestions for improvements. I'll leave this up for a couple of days. If I don't get any traction, I'll just go ahead and publish this latest enhancement as-is.

You can install just this enhanced version by using this manifest URL: https://raw.githubusercontent.com/orcnog/autocomplete-whisper/shift-click-v2/module.json

**Comment by orcnog** [comment]
This functionality was implemented.
