### ISSUE TITLE
Updating to version 1.0.2 yields version 1.0.1

### ISSUE THREAD

**Issue by diwako** [orcnog/autocomplete-whisper#47]
When ever I check for an update in modules, this module says it has an updated, but is always updates to version 1.0.1 from version 1.0.1

![image](https://user-images.githubusercontent.com/8259498/188816098-e58f80bf-0887-4cb4-9852-8068581970bb.png)

Foundry version: 10 - Build 284

The issue appears to be that the downloaded zip file for 1.0.2 contains the 1.0.1 version.

**Comment by r-valyar** [comment]
Was about to report the same issue. Module updates to itself.

**Comment by ThingsCouldGetDicey** [comment]
same issue

**Comment by AsianDumpring** [comment]
Also same issue with Foundry V9 build 280

**Comment by orcnog** [comment]
Fixed with release 1.0.3
